micronaut:
  application:
    name: kafka-ui
netty:
  default:
    allocator:
      max-order: 3

kafka:
  bootstrap.servers: localhost:9092

r2dbc:
  datasources:
    default:
      url: r2dbc:h2:mem:///testdb;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ''
