micronaut:
  server.port: 8080
  application:
    name: kafka-ui
  router:
    static-resources:
      static:
        paths:
          - file:${kafka-ui.ui-dir}

kafka-ui:
  ui-dir: ui/build

netty:
  default:
    allocator:
      max-order: 3

kafka:
  bootstrap.servers: localhost:9092
  schema.registry.url: http://localhost:8081

r2dbc:
  datasources:
    default:
      url: r2dbc:h2:mem:///testdb;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ''
